dbfilename redis_queue.rdb
dir /home/lisian/trash2/frappe-bench/config/pids
pidfile /home/lisian/trash2/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/lisian/trash2/frappe-bench/config/redis_queue.acl
